# Generated by Django 3.1 on 2020-11-26 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_number', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databasesite.department')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_number', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databasesite.employee')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databasesite.item')),
            ],
        ),
        migrations.CreateModel(
            name='Lott',
            fields=[
                ('Lott_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('warehouse_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databasesite.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databasesite.lott'),
        ),
    ]
