# Generated by Django 3.1 on 2020-11-26 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databasesite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='lot',
            new_name='lott',
        ),
        migrations.RenameField(
            model_name='lott',
            old_name='Lott_number',
            new_name='lott_number',
        ),
    ]
