# Generated by Django 3.1.3 on 2020-11-26 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databasesite', '0002_auto_20201126_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='department_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='department_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='lott',
            old_name='lott_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='warehouse_number',
            new_name='number',
        ),
    ]
