# Generated by Django 3.1 on 2020-11-28 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databasesite', '0003_auto_20201128_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proj_order', to='databasesite.project'),
        ),
    ]
